### ISSUE TITLE
rspm + renv workflow when switching between OSs

### ISSUE THREAD

**Issue by grantmcdermott** [Enchufa2/rspm#14]
Hi @Enchufa2,

I've been trying the `rspm` + `renv` workflow that you describe in the README. I'm running into an issue, which I think is likely a function of switching between operating systems. (_TL;DR_ I do my code prototyping on a work laptop running Mac OS, but then move to Amazon Linux 2 / CentOS 7 for the actual computation in the cloud. Everything is synched via Git.)

The issue is that the `renv.lock` file records the source repository as CRAN when I initialise the project, since I'm on a Mac. But once I switch over to my Linux VM, it doesn't correct this source to run through the `rspm` infrastructure. So I end installing libraries from source via CRAN instead of grabbing the pre-compiled binaries from RSPM.

To be explicit, here's the head of my `renv.lock` file. Note that I initialised the projected with `rspm::renv_int()` (but again from MacOS).

```r
{
  "R": {
    "Version": "4.2.2",
    "Repositories": [
      {
        "Name": "CRAN",
        "URL": "https://cloud.r-project.org"
      }
    ]
  },
  "Packages": {
...
```

And the project `.Rprofile` file is simply:

```r
source("renv/activate.R")
```

So, no `rspm::enable()`, but my understanding is that this is meant to actioned through `renv/activate`.

FWIW, when I open the project (in both Mac and on Linux) I get the following warning message, which is triggered by running `source(renv/activate.R)`

```
Warning messages:
1: In eval(quote({ : ignoring recursive attempt to run renv autoloader
2: In file(file, "rt") :
  cannot open file '/etc/os-release': No such file or directory
```

I'm stumped. Any ideas?

**Comment by Enchufa2** [comment]
Initializing the project via `rspm::renv_init()`, among other things, modifies the `renv/activate.R` file, which should be sync'ed too, to add [this](https://github.com/Enchufa2/rspm/blob/main/inst/resources/activate.R). RSPM activation is enclosed in a `try` block, but certainly I could use a `suppressWarnings` too. macOS is not supported (does RSPM provide binaries for macOS?). But it should work for Amazon Linux 2... if there is a `/etc/os-release` file. This file should exist there. It is how the package knows what to do.

**Comment by grantmcdermott** [comment]
Thanks. I'll do a bit more investigating and get back to you. (Sorry for the slow reply.)

**Comment by Enchufa2** [comment]
I published a new release, let me know if the issue persists.

**Comment by grantmcdermott** [comment]
Thanks @Enchufa2. I'll test this weekend.

**Comment by grantmcdermott** [comment]
Just got a chance to test.

The good news is that the `autoloader` warning message is now gone. Thanks for fixing that.

Unfortunately, the mirror/repo mismatch is still persisting. As you can see from the screenshot below, the project's CRAN repo designation (again due to the fact that I initialized the project on a Mac) overrides my Linux cloud desktop's RSPM repo designation (set as part of my global .Rprofile) and is building these packages from source. 

But! I think we're closer to pinning down the problem... I noticed something odd, namely that running `renv::restore` actually seems to override the additional text that `rspm::renv_init()` added to `renv/activate.R` in the first place. You can see that in the Git diff, which is highlighted in the top of the screenshot.

<img width="1920" alt="rspm-renv" src="https://user-images.githubusercontent.com/10285037/230478365-c82d07bf-9ab9-473e-ab4b-8f60d7a9929b.png">

FWIW this overwriting behaviour also seems to happen if I run `renv::restore()` on the original repo that I initialized the project on (i.e., on my Mac). So perhaps it is not an OS thing after all...

**Comment by Enchufa2** [comment]
For projects that are not necessarily created using our wrapper, I think that the best approach is to set the `RENV_CONFIG_REPOS_OVERRIDE` env variable to the RSPM URL, then restore, then call `rspm::install_sysreqs()` manually. See this workflow: https://github.com/Enchufa2/rspm/issues/17#issuecomment-1493129113

**Comment by grantmcdermott** [comment]
Cool, I agree that's probably the best path forward. (And is essentially what I had been doing manually before, as per this example: https://github.com/grantmcdermott/renv-rspm#details.)

Closing then. Thanks again, Iñaki. 

PS. I do think the `renv::restore` overwriting behaviour is worth thinking about separately, though. Perhaps not much that you can do from the rspm side. But a note to users might be worthwhile, since restoring the project is a common part of the renv workflow&mdash;e.g., reverting packages after a package update breaks unit tests&mdash; even when it isn't about collaboration or sharing codebases across systems.
