### ISSUE TITLE
invalid version specification ‘7’

### ISSUE THREAD

**Issue by pakiessling** [Enchufa2/rspm#16]
Hi, I installed rspm on Centos 7 via remotes on R 4.2.3 in a Conda enviroment.

Unfortunately I receive  the following error:

> rspm::enable()
Error: invalid version specification ‘7’

Any ideas?

**Comment by Enchufa2** [comment]
Unfortunately, I have no idea, I don't use Conda. As you can see in my [workflows](https://github.com/Enchufa2/rspm/blob/main/.github/workflows/build.yml#L12-L18), the package is checked for every commit in CentOS 7, 8 and 9, and it works. So this must be some issue in the Conda environment.

**Comment by Enchufa2** [comment]
Closing here. Please feel free to reopen if you find there's actually some issue in rspm.

**Comment by pakiessling** [comment]
Hi @Enchufa2 I tried again with a fresh R install outside of conda.

I still receive the same error.

`cat /etc/os-release` output:

```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

How are you probing for os version and is this different from what is returned by my `os-release`?

**Comment by Enchufa2** [comment]
[Here's how](https://github.com/Enchufa2/rspm/blob/6fce907885b38dc4e403e6091aff612dd7034644/R/integration.R#L76-L93). It uses `/etc/os-release`.

**Comment by pakiessling** [comment]
@Enchufa2 Thanks 

Looks like my id gets correctly set to `centos`. My os$VERSION_ID gets reported as "7" which throws an error with `package_version("7")`
I do not know enough about R to tell where the error lies. I guess I will overwrite my integration.R for now

**Comment by Enchufa2** [comment]
Thanks, that is indeed an issue. I'll fix it and send an update to CRAN ASAP.

**Comment by Enchufa2** [comment]
On CRAN now.
