### ISSUE TITLE
Cannot `enable()` on Amazon Sagemaker (Amazon Linux 2)

### ISSUE THREAD

**Issue by grantmcdermott** [Enchufa2/rspm#7]
Hi Inaki,

Following on from our email conversation, I'm having trouble enabling **rspm** on [Amazon Sagemaker](https://aws.amazon.com/sagemaker/). Essentially, this is just an Amazon Linux 2 image running on an EC2 instance, but with some bundled configurations and programs (mostly related to machine learning libraries, but including Jupyter notebooks as the default interface).

Specifically, I'm confronted by the following error:

```r
rspm::enable()

#> Downloading and installing required utilities...

#> Error: something went wrong, utilities not available
#> Traceback:
#> 
#> 1. rspm::enable()
#> 2. check_requirements()
#> 3. stop("something went wrong, utilities not available", call. = FALSE)
```

Stepping through `check_requirements()` manually, it looks like the problem is that the code cannot locate the patchelf binary.

```
# Context: rspm:::check_requirements()

preqs <- get(paste0(os()$id, "_requirements"), asNamespace("rspm"))
preqs <- Sys.which(preqs)
if (length(x <- names(preqs)[preqs == ""]))
   stop("please, install the following required utilities: ", x, call.=FALSE)
reqs <- c("ldd", "patchelf")
reqs <- Sys.which(reqs)
idx <- reqs == ""
names(reqs)[idx] <- file.path(user_dir("usr/bin"), names(reqs)[idx])
(reqs <- Sys.which(names(reqs))) ## GM: adding parens for printing

#> ldd: '/usr/bin/ldd' /home/ec2-user/.local/share/R/rspm/usr/bin/patchelf: ''
```

I can continue stepping through but as you can see the patchelf binary path is already not located and this later triggers an the error message [here](https://github.com/Enchufa2/rspm/blob/main/R/utils.R#L35).

FWIW, I can confirm that `~/.local/share/R/rspm` exists but it is empty.

```r
system("ls -al /home/ec2-user/.local/share/R/rspm", intern = TRUE) ## Aside: need intern=TRUE on Notebooks

#> 'total 0''drwxr-xr-x 2 ec2-user ec2-user  6 Aug  3 16:37 .''drwxr-xr-x 3 ec2-user ec2-user 18 Aug  3 16:37 ..'
```

Could this be a `.libPaths()` or Notebook thing, where the patchelf binary should get built/installed somewhere else?

```r
.libPaths()

#> '/home/ec2-user/anaconda3/envs/R/lib/R/library'

system("ls -al ~/anaconda3/bin/patchelf", intern = TRUE)

#> '-rwxrwxr-x 1 ec2-user ec2-user 187208 Mar 18 15:08 /home/ec2-user/anaconda3/bin/patchelf'
```

**Comment by Enchufa2** [comment]
But you don't have EPEL there, and not even yum... This package won't work there, sorry. Anyways, it makes little sense to try to install RSPM packages into a conda environment, because they are not built against the libraries you have there. You'll have to manage R and all the packages from conda.

**Comment by grantmcdermott** [comment]
Ugh, Notebooks and Conda. Totally new workflow for me and not one I'm particularly enjoying.

Closing, thanks.
