### ISSUE TITLE
Error when using `rspm::enable()` in .Rprofile

### ISSUE THREAD

**Issue by PMassicotte** [Enchufa2/rspm#8]
Following the installation instructions, I have edited my `.Rprofile` as this:

```r
rspm::enable() # wrap it in suppressMessages() to suppress the initial message
```
However, I have this error message when I restart R: 

![Peek 2022-08-06 09-44](https://user-images.githubusercontent.com/4519221/183251603-ef6894c5-045e-4623-9900-f55a0538d201.gif)

It works fine if I run `rspm::enable()` manually.

Any ideas?

```r
> sessionInfo()
R version 4.2.1 (2022-06-23)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 22.04.1 LTS
``

**Comment by Enchufa2** [comment]
Thanks, it should be fixed now.

**Comment by PMassicotte** [comment]
I confirm, fixed. Thank you.
